### ISSUE TITLE
deb package fails to install

### ISSUE THREAD

**Issue by romange** [GoogleCloudPlatform/compute-virtual-ethernet-linux#29]
when installing the released gve-dkms_1.2.3_all.deb package on ubuntu 21.10 I get

```
Error! Bad return status for module build on kernel: 5.13.0-1006-gcp (x86_64)
Consult /var/lib/dkms/gve/1.2.3/build/make.log for more information.
dpkg: error processing package gve-dkms (--configure):
```
Attaching make.log with compilation errrors

[make.log](https://github.com/GoogleCloudPlatform/compute-virtual-ethernet-linux/files/7532239/make.log)

**Comment by romange** [comment]
@DavMila  can you please help? 
```
DKMS make.log for gve-1.2.3 for kernel 5.13.0-1007-gcp (x86_64)
Sat Dec  4 20:06:56 UTC 2021
make -C /lib/modules/5.13.0-1007-gcp/build M=$PWD
make[1]: Entering directory '/usr/src/linux-headers-5.13.0-1007-gcp'
  CC [M]  /var/lib/dkms/gve/1.2.3/build/gve_main.o
  CC [M]  /var/lib/dkms/gve/1.2.3/build/gve_tx.o
  CC [M]  /var/lib/dkms/gve/1.2.3/build/gve_rx.o
  CC [M]  /var/lib/dkms/gve/1.2.3/build/gve_ethtool.o
  CC [M]  /var/lib/dkms/gve/1.2.3/build/gve_adminq.o
/var/lib/dkms/gve/1.2.3/build/gve_ethtool.c:13:36: warning: ‘struct ethtool_drvinfo’ declared inside parameter list will not be visible outside of this definition or declaration
   13 |                             struct ethtool_drvinfo *info)
      |                                    ^~~~~~~~~~~~~~~
/var/lib/dkms/gve/1.2.3/build/gve_ethtool.c: In function ‘gve_get_drvinfo’:
/var/lib/dkms/gve/1.2.3/build/gve_ethtool.c:17:21: error: invalid use of undefined type ‘struct ethtool_drvinfo’
   17 |         strlcpy(info->driver, "gve", sizeof(info->driver));
```

**Comment by DavMila** [comment]
Thanks for bringing this up. I'll take a look.
